networks:
  mynet:

services:
  nginx:
    build: ./images/nginx
    container_name: nginx
    ports:
        - "80:80"
        - "443:443"
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./www:/var/www
      - ./logs/nginx:/var/logs/nginx
    links:
      - php
    networks:
      - mynet

  php:
    build: ./images/php
    container_name: php
    volumes:
        - ./www:/var/www
    links:
        - mysql
    networks:
      - mynet

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - ./etc/mysql:/etc/mysql
      - ./logs/mysql:/var/log/mysql
      - ./mysql:/var/lib/mysql
      - ./mysql-files:/var/lib/mysql-files
      - ./entrypoint:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    networks:
      - mynet

  rabbitmq:
    hostname: 'dev-rabbitmq'
    image: rabbitmq:3.11-management
    container_name: 'rabbitmq'
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - '~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/mnesia/'
    environment:
      RABBITMQ_DEFAULT_USER: rmq_test
      RABBITMQ_DEFAULT_PASS: rmq_test
    networks:
      - mynet

  phpunit:
    image: php:7.4-cli
    container_name: phpunit
    volumes:
      - ./www/app.test:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit
    networks:
      - mynet

  phpmyadmin:
    image: phpmyadmin:5.2.0-apache
    container_name: phpmyadmin
    restart: unless-stopped
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql-files:/var/lib/mysql-files
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST= mysql
    links:
      - mysql
    networks:
      - mynet
